In [4]:
import pandas as pd
df = pd.read_csv("csic2010_requests.csv")
df.head()

,label,method,url,http_version,host,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,cookie,content_type,content_length,connection,body,classification
0,Anomalous,POST,/tienda1/publico/caracteristicas.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=EB808D6CB80736FF908D704C1B749A7B,application/x-www-form-urlencoded,Content-Length: 5,Connection: close,idA=2,1
1,Normal,GET,/tienda1/miembros/imagenes/ogono.jpg,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=FDC7D99F5F76056DB0AF6D58232FA236,NaN,NaN,close,NaN,0
2,Normal,POST,/tienda1/publico/vaciar.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=0334864C3129B4055611F1BDBA9CEF6F,application/x-www-form-urlencoded,Content-Length: 17,Connection: close,B2=Vaciar+carrito,0
3,Normal,GET,/tienda1/index.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=F64546A3AE2AF63281BCA92E0626314B,NaN,NaN,close,NaN,0
4,Normal,GET,/tienda1/global/titulo.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=5C532BCAB899D0BDD669E258DB5E3317,NaN,NaN,close,NaN,0

In [5]:
df['label'].value_counts()

label
Normal       5895
Anomalous    4105
Name: count, dtype: int64

In [6]:
df['url_length'] = df['url'].str.len()
df.groupby('label')['url_length'].describe()

            count       mean        std   min   25%   50%   75%    max
label
Anomalous  4066.0  77.487703  94.576060   1.0  27.0  33.0  91.0  865.0
Normal     5895.0  50.535199  61.990671  18.0  27.0  29.0  37.0  332.0